[taky]
hostname = MacBookPro.home
node_id = TAKY
bind_ip = 0.0.0.0
public_ip = 192.168.1.32
redis
root_dir = .

[cot_server]
port = 8089
mon_ip
mon_port
log_cot
max_persist_ttl = -1

[dp_server]
upload_path = ./dp-user

[ssl]
enabled = true
client_cert_required = True
ca = ./ssl/ca.crt
ca_key = ./ssl/ca.key
server_p12 = ./ssl/server.p12
server_p12_pw = atakatak
cert = ./ssl/server.crt
key = ./ssl/server.key
key_pw
cert_db = ./ssl/cert-db.txt

